### PR TITLE
Downloader.py added to get live data

### PR DESCRIPTION
**Pull request by vick2592**
The downloader.py script is used to constantly fetch new data on a selected time frame when called. The code is currently setup to work with the 4H timeframe that you used. I also did not change any names and kept the csv file name the same to not get any conflicts. Also, I updated the requriements.txt file to add the requests' library, as well as a couple other ones that might be useful going forward. 

Please review this code and let me know on the next steps where I can help with this project. For now, I will train the data and test it accordingly.

### CODE REVIEW

**Comment by pythonlessons** [comment]
Thanks I'll check this in coming days

**Comment by pythonlessons** [comment]
why you were developing on top of build/lib/finrock instead of doing it directly with finrock?
Now I am doing some workarounds to find changes you added

**Comment by pythonlessons** [comment]
I merged it to developOld branch, I'll walk through your changes and I'll check them more closely

**Comment by vick2592** [comment]
Cool, looking forward to it. Regarding the developing on top of build/lib/finrock, I am not sure actually why it separated the path during fork. Could be something my Visual Studio environment did. However, the updater.py script that I wanted to use to initiate the pull of new data I placed in the correct Finrock path. I will try to replicate the fork again and keep a lookout why this build folder is created. Thank you for pointing this out.

**Pull request merged**
